init:
  - git config --global core.autocrlf true

install:
  - cinst -y php -i
  - SET PATH=c:\tools\php;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci-test

build: off
